# this is to be a nested cf doc

# first is the application environment
# - ecr repo
# - batch job def

# then is the code pipeline

AWSTemplateFormatVersion: "2010-09-09"
Resources:

  

  myStackWithParams:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/cloudformation-templates-us-east-2/EC2ChooseAMI.template"
      Parameters:
        InstanceType: "t1.micro"
        KeyName: "mykey"