Description: >
  Docker Batch Configuration

#Parameters:

#Metadata:

Resources:

  BatchJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName: batch-test-cf
      ContainerProperties:
        Image: 089600871681.dkr.ecr.us-west-1.amazonaws.com/batch-test:latest
        Vcpus: 1
        Memory: 2000
        Command: ["echo", "Hello World"]
      RetryStrategy:
        Attempts: 1

  BatchJobCompute:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeEnvironmentName: batch-test-compute-cf
      Type: MANAGED
      ServiceRole: arn:aws:iam::089600871681:role/service-role/AWSBatchServiceRole
      ComputeResources:
        Type: EC2
        MinvCpus: 0
        MaxvCpus: 64
        DesiredvCpus: 0
        InstanceTypes:
          - optimal
        Subnets:
          - subnet-d2971c8a
          - subnet-ad176fc9
        SecurityGroupIds:
          - sg-15583372
        InstanceRole: arn:aws:iam::089600871681:instance-profile/ecsInstanceRole

  BatchJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      Priority: 1
      JobQueueName: batch-test-cf
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchJobCompute